// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_d7WCS8HryFJetepgtubQvCC_-Un6yRM',
    appId: '1:857920531708:web:a3c29ccd2d28186b9b3b79',
    messagingSenderId: '857920531708',
    projectId: 'maestro203311023',
    authDomain: 'maestro203311023.firebaseapp.com',
    storageBucket: 'maestro203311023.appspot.com',
    measurementId: 'G-EJDQPHT019',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrQIDBPbkP-wjVVxMK9z_Su3Cg7a7l6O8',
    appId: '1:857920531708:android:4654e4cd55608cf79b3b79',
    messagingSenderId: '857920531708',
    projectId: 'maestro203311023',
    storageBucket: 'maestro203311023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXWHEewlZUqOd-0jJrqh31hoV3-AKX_rU',
    appId: '1:857920531708:ios:a2386f37beb2f0d19b3b79',
    messagingSenderId: '857920531708',
    projectId: 'maestro203311023',
    storageBucket: 'maestro203311023.appspot.com',
    iosClientId: '857920531708-d174nnlh3qb96v81h8obq2vhs2u42b92.apps.googleusercontent.com',
    iosBundleId: 'com.example.maestro2',
  );
}
